# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: terraform-provider-kops
before:
  hooks:
    - go mod download
builds:
  - id: terraform-provider-kops
    main: ./cmd/terraform-provider-kops
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X 'github.com/terraform-kops/terraform-provider-kops/pkg/version.BuildVersion={{.Version}}'
      - -X 'github.com/terraform-kops/terraform-provider-kops/pkg/version.BuildCommit={{.Commit}}'
      - -X 'github.com/terraform-kops/terraform-provider-kops/pkg/version.BuildDate={{.Date}}'
      - -X 'github.com/terraform-kops/terraform-provider-kops/pkg/version.BuiltBy=goreleaser'
archives:
  - id: terraform-provider-kops
    formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    ids:
      - terraform-provider-kops
    files:
      - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  prerelease: auto
signs:
  - id: terraform-provider-kops
    artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: asc
