# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: [ "main" ]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.TAGPR_APP_ID }}
        private-key: ${{ secrets.TAGPR_APP_PRIVATE_KEY }}
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        token: ${{ steps.generate-token.outputs.token }}
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
